export default function About() {
    return (
        <main className="about">
            <h1>About</h1>
            <h2>Introducing ExpressBlog: A Blog Post Project Using a Custom API</h2>

            <p><strong>ExpressBlog</strong> is a web application that allows users to read and create blog posts. The application uses a custom API created using <strong>Express</strong>, <strong>Mongoose</strong>, <strong>MongoDB</strong>, and <strong>JWT tokens</strong> for authentication.</p>
            <p>The API features a <strong>RESTful</strong> architecture that allows for easy consumption and manipulation of data. It provides endpoints for retrieving, creating, updating, and deleting blog posts, as well as endpoints for creating and managing user accounts. JWT tokens are used to authenticate users and authorize them to perform certain actions, such as creating or updating blog posts.</p>
            <p>The front-end of the application was built using <strong>React</strong>, and features a responsive design that adapts to various screen sizes. Users can read blog posts, leave comments, and create their own posts using a simple and intuitive interface. The front-end communicates with the API using https requests, and JWT tokens are stored in local storage to maintain user authentication across sessions.</p>
            <p>The back-end of the application was built using <strong>Express</strong> and is hosted on railway.com. It uses <strong>Mongoose</strong> to interact with a <strong>MongoDB</strong> database, where blog posts and user accounts are stored. The API is secured using JWT tokens, and passwords are encrypted using a hashing algorithm to ensure that user data is secure.</p>
            <p><strong>ExpressBlog</strong> was created as a way to showcase my capabilities as a web developer and API creator. It demonstrates my proficiency in <strong>Express</strong>, <strong>Mongoose</strong>, <strong>MongoDB</strong>, <strong>JWT tokens</strong>, and <strong>React</strong>, as well as your ability to create an intuitive and user-friendly interface.</p>
            <p>The blog posts featured in the application were generated by me, <strong>ChatGPT</strong>, based on various topics such as technology, science, culture, and more. These blog posts provide engaging and informative content for users to read and discuss.</p>
            <p>Overall, <strong>ExpressBlog</strong> is an impressive example of the power of custom APIs and their ability to enable the creation of dynamic and engaging web applications. It showcases my skills as a web developer and API creator, while providing a valuable resource for users to read and create engaging blog content.</p>
            <p>If you're interested in learning more about <strong>ExpressBlog</strong> or my services as a web developer and API creator, please feel free to contact me directly via <a href="mailto:orlandojose729@gmail.com">orlandojose729@gmail.com</a>.</p>
        </main>
    )
}